# TODO: CHANGE
services:
  metro-graph-frontend:
    container_name: portfolio-fe
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio-fe:latest
    ports:
      - "5174:5174"